### ISSUE TITLE
Lịch thi THPTQG dự kiến sắp thay đổi vào cuối tháng 6

### ISSUE THREAD

**Issue by Rookie001MC** [anhkhoatqt11/demnguockithi#3]
https://www.facebook.com/CoVuMaiPhuong/posts/767055174649560

**Comment by anhkhoatqt11** [comment]
Thời gian trên trang web sẽ được cập nhật khi có văn bản chính thức về việc Hướng dẫn thi tốt nghiệp THPT năm 2022 từ Bộ Giáo dục và Đào tạo bạn nhé.

**Comment by Rookie001MC** [comment]
Closed vì Bộ Giáo dục đã thay đổi lịch thi dự kiến vào tháng 7.
